<?php

defined('MOODLE_INTERNAL') || die();


function xmldb_block_ifcare_install() {
    global $DB;

// AEQ CLASS INSERTS.
$records_aeq_class = [
    (object)['id' => 1, 'nome_classe' => 'Emoções Relacionadas às aulas'],
    (object)['id' => 2, 'nome_classe' => 'Emoções Relacionadas ao aprendizado'],
    (object)['id' => 3, 'nome_classe' => 'Emoções Relacionadas às atividades avaliativas']
];

foreach ($records_aeq_class as $record) {
    $DB->insert_record('ifcare_classeaeq', $record);
}

// EMOTIONS-CLASS INSERTS.
$records_emotions = [
    (object)['id' => 1, 'classeaeq_id' => 1, 'nome' => 'Alegria', 'txttooltip' => 'Uma sensação de satisfação e bem-estar, normalmente associada a experiências agradáveis e positivas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 2, 'classeaeq_id' => 1, 'nome' => 'Esperança', 'txttooltip' => 'Um sentimento otimista sobre o futuro, acreditando que algo bom vai acontecer.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 3, 'classeaeq_id' => 1, 'nome' => 'Orgulho', 'txttooltip' => 'Um sentimento de satisfação consigo mesmo ou com os outros por realizações, sucesso ou habilidades.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 4, 'classeaeq_id' => 1, 'nome' => 'Raiva', 'txttooltip' => 'Uma emoção intensa, muitas vezes resultante de frustração ou injustiça, que pode levar a ações impulsivas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 5, 'classeaeq_id' => 1, 'nome' => 'Ansiedade', 'txttooltip' => 'Um sentimento de preocupação, nervosismo ou medo sobre eventos futuros ou situações incertas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 6, 'classeaeq_id' => 1, 'nome' => 'Vergonha', 'txttooltip' => 'Um sentimento desconfortável ou doloroso causado pela percepção de que algo que você fez ou disse foi errado ou embaraçoso.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 7, 'classeaeq_id' => 1, 'nome' => 'Desespero', 'txttooltip' => 'Um sentimento de completa falta de esperança, onde parece que não há soluções ou saídas para uma situação difícil.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 8, 'classeaeq_id' => 1, 'nome' => 'Tédio', 'txttooltip' => 'Um estado de falta de interesse ou estímulo, muitas vezes associado à repetição ou à ausência de desafios.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 9, 'classeaeq_id' => 2, 'nome' => 'Alegria', 'txttooltip' => 'Uma sensação de satisfação e bem-estar, normalmente associada a experiências agradáveis e positivas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 10, 'classeaeq_id' => 2, 'nome' => 'Esperança', 'txttooltip' => 'Um sentimento otimista sobre o futuro, acreditando que algo bom vai acontecer.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 11, 'classeaeq_id' => 2, 'nome' => 'Orgulho', 'txttooltip' => 'Um sentimento de satisfação consigo mesmo ou com os outros por realizações, sucesso ou habilidades.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 12, 'classeaeq_id' => 2, 'nome' => 'Raiva', 'txttooltip' => 'Uma emoção intensa, muitas vezes resultante de frustração ou injustiça, que pode levar a ações impulsivas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 13, 'classeaeq_id' => 2, 'nome' => 'Ansiedade', 'txttooltip' => 'Um sentimento de preocupação, nervosismo ou medo sobre eventos futuros ou situações incertas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 14, 'classeaeq_id' => 2, 'nome' => 'Vergonha', 'txttooltip' => 'Um sentimento desconfortável ou doloroso causado pela percepção de que algo que você fez ou disse foi errado ou embaraçoso.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 15, 'classeaeq_id' => 2, 'nome' => 'Desespero', 'txttooltip' => 'Um sentimento de completa falta de esperança, onde parece que não há soluções ou saídas para uma situação difícil.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 16, 'classeaeq_id' => 2, 'nome' => 'Tédio', 'txttooltip' => 'Um estado de falta de interesse ou estímulo, muitas vezes associado à repetição ou à ausência de desafios.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 17, 'classeaeq_id' => 3, 'nome' => 'Alegria', 'txttooltip' => 'Uma sensação de satisfação e bem-estar, normalmente associada a experiências agradáveis e positivas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 18, 'classeaeq_id' => 3, 'nome' => 'Esperança', 'txttooltip' => 'Um sentimento otimista sobre o futuro, acreditando que algo bom vai acontecer.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 19, 'classeaeq_id' => 3, 'nome' => 'Orgulho', 'txttooltip' => 'Um sentimento de satisfação consigo mesmo ou com os outros por realizações, sucesso ou habilidades.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 20, 'classeaeq_id' => 3, 'nome' => 'Alívio', 'txttooltip' => 'Um sentimento de tranquilidade e conforto que surge quando uma situação estressante, difícil ou dolorosa chega ao fim ou é resolvida.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 21, 'classeaeq_id' => 3, 'nome' => 'Raiva', 'txttooltip' => 'Uma emoção intensa, muitas vezes resultante de frustração ou injustiça, que pode levar a ações impulsivas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 22, 'classeaeq_id' => 3, 'nome' => 'Ansiedade', 'txttooltip' => 'Um sentimento de preocupação, nervosismo ou medo sobre eventos futuros ou situações incertas.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 23, 'classeaeq_id' => 3, 'nome' => 'Vergonha', 'txttooltip' => 'Um sentimento desconfortável ou doloroso causado pela percepção de que algo que você fez ou disse foi errado ou embaraçoso.', 'antes' => 1, 'durante' => 1, 'depois' => 1],
    (object)['id' => 24, 'classeaeq_id' => 3, 'nome' => 'Desespero', 'txttooltip' => 'Um sentimento de completa falta de esperança, onde parece que não há soluções ou saídas para uma situação difícil.', 'antes' => 1, 'durante' => 1, 'depois' => 1]
];

foreach ($records_emotions as $record) {
    $DB->insert_record('ifcare_emocao', $record);
}

$records_questions = [
    (object)['id' => 1, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estar na aula dessa disciplina me deixa muito animado.'],
    (object)['id' => 2, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Gosto de estar nesta aula.'],
    (object)['id' => 3, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Depois dessa aula, começo a ansiar pela próxima aula.'],
    (object)['id' => 4, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou ansioso(a) para aprender muito nesta aula.'],
    (object)['id' => 5, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou feliz por ter entendido o conteúdo da disciplina.'],
    (object)['id' => 6, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico contente que valeu a pena ir à aula.'],
    (object)['id' => 7, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou motivado(a) para ir a esta aula porque é empolgante.'],
    (object)['id' => 8, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Meu prazer nesta aula me faz querer participar.'],
    (object)['id' => 9, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'É tão empolgante que eu poderia ficar na aula por horas ouvindo o professor.'],
    (object)['id' => 10, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Gosto tanto de participar que fico energizado(a).'],
    (object)['id' => 11, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou confiante quando vou à aula.'],
    (object)['id' => 12, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou cheio(a) de esperança.'],
    (object)['id' => 13, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou otimista de que conseguirei acompanhar o material.'],
    (object)['id' => 14, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou esperançoso(a) de que farei boas contribuições na aula.'],
    (object)['id' => 15, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou confiante porque entendo o material.'],
    (object)['id' => 16, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estar confiante de que entenderei o material me motiva.'],
    (object)['id' => 17, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Minha confiança me motiva a me preparar para a aula.'],
    (object)['id' => 18, 'emocao_id' => 2, 'classeaeq_id' => 1, 'pergunta_texto' => 'Minhas esperanças de que terei sucesso me motivam a investir muito esforço.'],
    (object)['id' => 19, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Tenho orgulho de mim mesmo(a).'],
    (object)['id' => 20, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Tenho orgulho de conseguir acompanhar o material.'],
    (object)['id' => 21, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Tenho orgulho de fazer melhor do que os outros neste curso.'],
    (object)['id' => 22, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Acho que posso ter orgulho do que sei sobre este assunto.'],
    (object)['id' => 23, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou orgulhoso(a) das contribuições que fiz na aula.'],
    (object)['id' => 24, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando faço boas contribuições na aula, fico ainda mais motivado(a).'],
    (object)['id' => 25, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque tenho orgulho das minhas conquistas neste curso, estou motivado(a) a continuar.'],
    (object)['id' => 26, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Gostaria de contar aos meus amigos sobre como me saí bem neste curso.'],
    (object)['id' => 27, 'emocao_id' => 3, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando me saio bem na aula, meu coração se enche de orgulho.'],
    (object)['id' => 28, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto-me frustrado(a) na aula.'],
    (object)['id' => 29, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou com raiva.'],
    (object)['id' => 30, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Pensar na baixa qualidade do curso me deixa irritado(a).'],
    (object)['id' => 31, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Pensar em todas as coisas inúteis que tenho que aprender me irrita.'],
    (object)['id' => 32, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando penso no tempo que perco na aula, fico agitado(a).'],
    (object)['id' => 33, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Eu gostaria de não ter que ir à aula porque isso me deixa com raiva.'],
    (object)['id' => 34, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Eu gostaria de poder dizer aos professores o que penso.'],
    (object)['id' => 35, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto a raiva crescendo dentro de mim.'],
    (object)['id' => 36, 'emocao_id' => 4, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque estou com raiva, fico inquieto(a) na aula.'],
    (object)['id' => 37, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Pensar na aula me deixa inquieto(a).'],
    (object)['id' => 38, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto medo.'],
    (object)['id' => 39, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto-me nervoso(a) na aula.'],
    (object)['id' => 40, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Mesmo antes da aula, me preocupo se conseguirei entender o material.'],
    (object)['id' => 41, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Me preocupo se estou suficientemente preparado(a) para a lição.'],
    (object)['id' => 42, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Me preocupo se as exigências podem ser grandes demais.'],
    (object)['id' => 43, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Me preocupo que os outros entenderão mais do que eu.'],
    (object)['id' => 44, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque estou tão nervoso(a), prefiro pular a aula.'],
    (object)['id' => 45, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Tenho medo de que possa dizer algo errado, então prefiro não dizer nada.'],
    (object)['id' => 46, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando penso na aula, fico enjoado(a).'],
    (object)['id' => 47, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico tenso(a) na aula.'],
    (object)['id' => 48, 'emocao_id' => 5, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando não entendo algo importante na aula, meu coração acelera.'],
    (object)['id' => 49, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico envergonhado(a).'],
    (object)['id' => 50, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou envergonhado(a).'],
    (object)['id' => 51, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Se os outros soubessem que não entendo o material, ficaria envergonhado(a).'],
    (object)['id' => 52, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando digo algo na aula, sinto que estou me fazendo de tolo(a).'],
    (object)['id' => 53, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou envergonhado(a) por não conseguir me expressar bem.'],
    (object)['id' => 54, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou envergonhado(a) porque os outros entenderam mais da palestra do que eu.'],
    (object)['id' => 55, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Depois que digo algo na aula, gostaria de poder me esconder.'],
    (object)['id' => 56, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Preferiria não contar a ninguém quando não entendo algo na aula.'],
    (object)['id' => 57, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando digo algo na aula, sinto que fico vermelho(a).'],
    (object)['id' => 58, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque fico envergonhado(a), fico tenso(a) e inibido(a).'],
    (object)['id' => 59, 'emocao_id' => 6, 'classeaeq_id' => 1, 'pergunta_texto' => 'Quando falo na aula, começo a gaguejar.'],
    (object)['id' => 60, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'O pensamento desta aula me faz sentir desamparado(a).'],
    (object)['id' => 61, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto-me desamparado(a).'],
    (object)['id' => 62, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Mesmo antes da aula, estou resignado(a) à ideia de que não conseguirei entender o material.'],
    (object)['id' => 63, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Perdi toda a esperança de entender esta aula.'],
    (object)['id' => 64, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto-me desamparado(a) para continuar neste programa de estudos.'],
    (object)['id' => 65, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque desisti, não tenho energia para ir à aula.'],
    (object)['id' => 66, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Preferiria não ir à aula, pois não há esperança de entender o material de qualquer forma.'],
    (object)['id' => 67, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'É inútil me preparar para a aula, já que não entendo o material de qualquer forma.'],
    (object)['id' => 68, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque não entendo o material, pareço desconectado(a) e resignado(a).'],
    (object)['id' => 69, 'emocao_id' => 7, 'classeaeq_id' => 1, 'pergunta_texto' => 'Sinto-me tão desamparado(a) que toda a minha energia se esgota.'],
    (object)['id' => 70, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico entediado(a).'],
    (object)['id' => 71, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Acho esta aula bastante maçante.'],
    (object)['id' => 72, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'A palestra me entedia.'],
    (object)['id' => 73, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Porque fico entediado(a), minha mente começa a vagar.'],
    (object)['id' => 74, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou tentado(a) a sair da palestra porque é tão chata.'],
    (object)['id' => 75, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Penso em outras coisas que poderia estar fazendo em vez de estar sentado(a) nesta aula chata.'],
    (object)['id' => 76, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Como o tempo se arrasta, olho frequentemente para o meu relógio.'],
    (object)['id' => 77, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico tão entediado(a) que tenho problemas para ficar alerta.'],
    (object)['id' => 78, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico inquieto(a) porque não posso esperar para que a aula termine.'],
    (object)['id' => 79, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Durante a aula, sinto que poderia afundar na minha cadeira.'],
    (object)['id' => 80, 'emocao_id' => 8, 'classeaeq_id' => 1, 'pergunta_texto' => 'Começo a bocejar na aula porque estou tão entediado(a).'],
    (object)['id' => 233, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico animado(a) para ir à aula.'],
    (object)['id' => 234, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Gosto de estar na aula.'],
    (object)['id' => 235, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Depois da aula, começo a ansiar pela próxima aula.'],
    (object)['id' => 236, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou ansioso(a) para aprender muito nesta aula.'],
    (object)['id' => 237, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou feliz por ter entendido o material.'],
    (object)['id' => 238, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Fico contente que valeu a pena ir à aula.'],
    (object)['id' => 239, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Estou motivado(a) para ir a esta aula porque é empolgante.'],
    (object)['id' => 240, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Meu prazer nesta aula me faz querer participar.'],
    (object)['id' => 241, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'É tão empolgante que eu poderia ficar na aula por horas ouvindo o professor.'],
    (object)['id' => 242, 'emocao_id' => 1, 'classeaeq_id' => 1, 'pergunta_texto' => 'Gosto tanto de participar que fico energizado(a).'],
    (object)['id' => 158, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou ansioso para estudar.'],
    (object)['id' => 159, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu gosto do desafio de aprender o material.'],
    (object)['id' => 160, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu gosto de adquirir novos conhecimentos.'],
    (object)['id' => 161, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu gosto de lidar com o material do curso.'],
    (object)['id' => 162, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Refletir sobre meu progresso nos estudos me deixa feliz.'],
    (object)['id' => 163, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu estudo mais do que o necessário porque gosto muito.'],
    (object)['id' => 164, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou tão feliz com o progresso que fiz que estou motivado a continuar estudando.'],
    (object)['id' => 165, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Certas matérias são tão agradáveis que estou motivado a fazer leituras adicionais sobre elas.'],
    (object)['id' => 166, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando meus estudos vão bem, isso me dá uma empolgação.'],
    (object)['id' => 167, 'emocao_id' => 9, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico fisicamente animado quando meus estudos vão bem.'],
    (object)['id' => 168, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu tenho uma visão otimista em relação ao estudo.'],
    (object)['id' => 169, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto confiante ao estudar.'],
    (object)['id' => 170, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto confiante de que serei capaz de dominar o material.'],
    (object)['id' => 171, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'Sinto-me otimista de que farei bons progressos nos estudos.'],
    (object)['id' => 172, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'O pensamento de alcançar meus objetivos de aprendizado me inspira.'],
    (object)['id' => 173, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'Meu senso de confiança me motiva.'],
    (object)['id' => 174, 'emocao_id' => 10, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou orgulhoso de mim mesmo.'],
    (object)['id' => 175, 'emocao_id' => 11, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou orgulhoso da minha capacidade.'],
    (object)['id' => 176, 'emocao_id' => 11, 'classeaeq_id' => 2, 'pergunta_texto' => 'Acho que posso me orgulhar das minhas conquistas nos estudos.'],
    (object)['id' => 177, 'emocao_id' => 11, 'classeaeq_id' => 2, 'pergunta_texto' => 'Porque quero me orgulhar das minhas conquistas, estou muito motivado.'],
    (object)['id' => 178, 'emocao_id' => 11, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando resolvo um problema difícil nos meus estudos, meu coração bate de orgulho.'],
    (object)['id' => 179, 'emocao_id' => 11, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando me destaco no meu trabalho, fico cheio de orgulho.'],
    (object)['id' => 180, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico com raiva quando tenho que estudar.'],
    (object)['id' => 181, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estudar me irrita.'],
    (object)['id' => 182, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico com raiva enquanto estudo.'],
    (object)['id' => 183, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou irritado por ter que estudar tanto.'],
    (object)['id' => 184, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico incomodado por ter que estudar.'],
    (object)['id' => 185, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Porque fico tão chateado com a quantidade de material, não quero nem começar a estudar.'],
    (object)['id' => 186, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico tão bravo que sinto vontade de jogar o livro didático pela janela.'],
    (object)['id' => 187, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando fico muito tempo sentado na minha mesa, minha irritação me deixa inquieto.'],
    (object)['id' => 188, 'emocao_id' => 12, 'classeaeq_id' => 2, 'pergunta_texto' => 'Depois de estudar por um longo período, fico tão irritado que fico tenso.'],
    (object)['id' => 189, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando olho para os livros que ainda tenho que ler, fico ansioso.'],
    (object)['id' => 190, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico tenso e nervoso enquanto estudo.'],
    (object)['id' => 191, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando não consigo acompanhar meus estudos, isso me deixa com medo.'],
    (object)['id' => 192, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me preocupo se serei capaz de lidar com todo o meu trabalho.'],
    (object)['id' => 193, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'O assunto me assusta, pois não o compreendo completamente.'],
    (object)['id' => 194, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me preocupo se entendi o material corretamente.'],
    (object)['id' => 195, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Fico tão nervoso que nem quero começar a estudar.'],
    (object)['id' => 196, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Enquanto estudo, sinto vontade de me distrair para reduzir minha ansiedade.'],
    (object)['id' => 197, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando tenho que estudar, começo a me sentir enjoado.'],
    (object)['id' => 198, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'À medida que o tempo acaba, meu coração começa a acelerar.'],
    (object)['id' => 199, 'emocao_id' => 13, 'classeaeq_id' => 2, 'pergunta_texto' => 'A preocupação em não completar o material me faz suar.'],
    (object)['id' => 200, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto envergonhado.'],
    (object)['id' => 201, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto envergonhado pela minha constante procrastinação.'],
    (object)['id' => 202, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto envergonhado por não conseguir absorver os detalhes mais simples.'],
    (object)['id' => 203, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto envergonhado porque não sou tão bom quanto os outros em estudar.'],
    (object)['id' => 204, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto envergonhado por não conseguir explicar completamente o material para os outros.'],
    (object)['id' => 205, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto envergonhado quando percebo que não tenho capacidade.'],
    (object)['id' => 206, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Minhas lacunas de memória me envergonham.'],
    (object)['id' => 207, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Porque tive tantas dificuldades com o material do curso, evito discutir sobre ele.'],
    (object)['id' => 208, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu não quero que ninguém saiba quando não consegui entender algo.'],
    (object)['id' => 209, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Quando alguém percebe o quanto eu pouco entendo, evito contato visual.'],
    (object)['id' => 210, 'emocao_id' => 14, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu fico vermelho quando não sei a resposta a uma pergunta relacionada ao material do curso.'],
    (object)['id' => 211, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto sem esperança quando penso em estudar.'],
    (object)['id' => 212, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto impotente.'],
    (object)['id' => 213, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto resignado.'],
    (object)['id' => 214, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou resignado ao fato de que não tenho capacidade para dominar este material.'],
    (object)['id' => 215, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Depois de estudar, estou resignado ao fato de que não tenho habilidade.'],
    (object)['id' => 216, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estou desencorajado pela ideia de que nunca aprenderei o material.'],
    (object)['id' => 217, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me preocupo porque minhas habilidades não são suficientes para meu curso de estudos.'],
    (object)['id' => 218, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu me sinto tão impotente que não consigo dar o meu máximo nos estudos.'],
    (object)['id' => 219, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu gostaria de poder desistir porque não consigo lidar com isso.'],
    (object)['id' => 220, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Minha falta de confiança me deixa exausto antes mesmo de começar.'],
    (object)['id' => 221, 'emocao_id' => 15, 'classeaeq_id' => 2, 'pergunta_texto' => 'Minha desesperança minou toda a minha energia.'],
    (object)['id' => 222, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'O material me entedia até a morte.'],
    (object)['id' => 223, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estudar para meus cursos me entedia.'],
    (object)['id' => 224, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Estudar é chato e monótono.'],
    (object)['id' => 225, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Enquanto estudo este material chato, passo o tempo pensando em como o tempo não passa.'],
    (object)['id' => 226, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'O material é tão chato que me pego sonhando acordado.'],
    (object)['id' => 227, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu percebo que minha mente divaga enquanto estudo.'],
    (object)['id' => 228, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Porque estou entediado, não tenho desejo de aprender.'],
    (object)['id' => 229, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Eu preferiria deixar este trabalho chato para amanhã.'],
    (object)['id' => 230, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Porque estou entediado, fico cansado sentado na minha mesa.'],
    (object)['id' => 231, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'O material me entedia tanto que me sinto exausto.'],
    (object)['id' => 232, 'emocao_id' => 16, 'classeaeq_id' => 2, 'pergunta_texto' => 'Enquanto estudo, pareço me distrair porque é tão chato.'],
    (object)['id' => 81, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto ansioso quando vou à aula.'],
    (object)['id' => 82, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu gosto de fazer a prova.'],
    (object)['id' => 83, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou ansioso para demonstrar meu conhecimento.'],
    (object)['id' => 84, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Fico feliz por conseguir lidar com o teste.'],
    (object)['id' => 85, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Para mim, o teste é um desafio que é agradável.'],
    (object)['id' => 86, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Porque gosto de me preparar para o teste, estou motivado a fazer mais do que é necessário.'],
    (object)['id' => 87, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Porque estou ansioso para ter sucesso, estudo muito.'],
    (object)['id' => 88, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Antes de fazer a prova, sinto uma sensação de expectativa.'],
    (object)['id' => 89, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Meu coração bate mais rápido de alegria.'],
    (object)['id' => 90, 'emocao_id' => 17, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu brilho de felicidade.'],
    (object)['id' => 91, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou otimista de que tudo vai dar certo.'],
    (object)['id' => 92, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou muito confiante.'],
    (object)['id' => 93, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Tenho grande esperança de que minhas habilidades serão suficientes.'],
    (object)['id' => 94, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou bastante confiante de que minha preparação é suficiente.'],
    (object)['id' => 95, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Penso na minha prova de forma otimista.'],
    (object)['id' => 96, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Começo a estudar para a prova com grande esperança e expectativa.'],
    (object)['id' => 97, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Minha confiança me motiva a me preparar bem.'],
    (object)['id' => 98, 'emocao_id' => 18, 'classeaeq_id' => 3, 'pergunta_texto' => 'Esperando ter sucesso, estou motivado a investir muito esforço.'],
    (object)['id' => 99, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou muito satisfeito comigo mesmo.'],
    (object)['id' => 100, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou orgulhoso de mim mesmo.'],
    (object)['id' => 101, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Acho que posso me orgulhar do meu conhecimento.'],
    (object)['id' => 102, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Pensar sobre meu sucesso me faz sentir orgulho.'],
    (object)['id' => 103, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou orgulhoso de quão bem eu lidei com a prova.'],
    (object)['id' => 104, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou tão orgulhoso da minha preparação que quero começar a prova agora.'],
    (object)['id' => 105, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'O orgulho pelo meu conhecimento alimenta meus esforços em fazer a prova.'],
    (object)['id' => 106, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Quando recebo os resultados do teste, meu coração bate com orgulho.'],
    (object)['id' => 107, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Depois da prova, me sinto como se estivesse mais alto porque estou tão orgulhoso.'],
    (object)['id' => 108, 'emocao_id' => 19, 'classeaeq_id' => 3, 'pergunta_texto' => 'Saio da prova com a aparência de um vencedor no meu rosto.'],
    (object)['id' => 109, 'emocao_id' => 20, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto aliviado.'],
    (object)['id' => 110, 'emocao_id' => 20, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto livre.'],
    (object)['id' => 111, 'emocao_id' => 20, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto muito aliviado.'],
    (object)['id' => 112, 'emocao_id' => 20, 'classeaeq_id' => 3, 'pergunta_texto' => 'A tensão no meu estômago está se dissipando.'],
    (object)['id' => 113, 'emocao_id' => 20, 'classeaeq_id' => 3, 'pergunta_texto' => 'Finalmente posso respirar aliviado novamente.'],
    (object)['id' => 114, 'emocao_id' => 20, 'classeaeq_id' => 3, 'pergunta_texto' => 'Posso finalmente rir novamente.'],
    (object)['id' => 115, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu fico bravo.'],
    (object)['id' => 116, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu estou bastante irritado.'],
    (object)['id' => 117, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu fico bravo com a pressão de tempo que não deixa tempo suficiente para me preparar.'],
    (object)['id' => 118, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu fico bravo com a quantidade de material que preciso saber.'],
    (object)['id' => 119, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu acho as perguntas injustas.'],
    (object)['id' => 120, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Fico bravo com os critérios de avaliação do professor.'],
    (object)['id' => 121, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu gostaria de poder dizer isso ao professor.'],
    (object)['id' => 122, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu gostaria de poder expressar minha raiva livremente.'],
    (object)['id' => 123, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Minha raiva faz meu sangue ferver.'],
    (object)['id' => 124, 'emocao_id' => 21, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu fico tão bravo que começo a sentir calor e ruborizar.'],
    (object)['id' => 125, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Antes da prova, me sinto nervoso e inquieto.'],
    (object)['id' => 126, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou muito nervoso.'],
    (object)['id' => 127, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto em pânico ao escrever a prova.'],
    (object)['id' => 128, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me preocupo se estudei o suficiente.'],
    (object)['id' => 129, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me preocupo se a prova será muito difícil.'],
    (object)['id' => 130, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me preocupo se vou passar na prova.'],
    (object)['id' => 131, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Fico tão nervoso que gostaria de poder pular a prova.'],
    (object)['id' => 132, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Fico tão nervoso que não consigo esperar que a prova acabe.'],
    (object)['id' => 133, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Estou tão ansioso que preferiria estar em qualquer outro lugar.'],
    (object)['id' => 134, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto enjoado.'],
    (object)['id' => 135, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'No início do teste, meu coração começa a disparar.'],
    (object)['id' => 136, 'emocao_id' => 22, 'classeaeq_id' => 3, 'pergunta_texto' => 'Minhas mãos ficam trêmulas.'],
    (object)['id' => 137, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto humilhado.'],
    (object)['id' => 138, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto envergonhado.'],
    (object)['id' => 139, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Não consigo nem pensar em como seria embaraçoso falhar na prova.'],
    (object)['id' => 140, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me envergonho da minha má preparação.'],
    (object)['id' => 141, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Fico envergonhado porque não consigo responder corretamente às perguntas.'],
    (object)['id' => 142, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Minhas notas me envergonham.'],
    (object)['id' => 143, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Fico tão envergonhado que quero correr e me esconder.'],
    (object)['id' => 144, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Quando recebo uma nota ruim, prefiro não enfrentar meu professor novamente.'],
    (object)['id' => 145, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Porque estou envergonhado, meu pulso acelera.'],
    (object)['id' => 146, 'emocao_id' => 23, 'classeaeq_id' => 3, 'pergunta_texto' => 'Quando os outros descobrem sobre minhas notas ruins, começo a corar.'],
    (object)['id' => 147, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu fico deprimido porque sinto que não tenho muita esperança para a prova.'],
    (object)['id' => 148, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto sem esperança.'],
    (object)['id' => 149, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu perdi toda a esperança de que tenho a habilidade de me sair bem na prova.'],
    (object)['id' => 150, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Desisti de acreditar que posso responder as perguntas corretamente.'],
    (object)['id' => 151, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Começo a pensar que, não importa o quanto eu tente, não terei sucesso no teste.'],
    (object)['id' => 152, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Começo a perceber que as perguntas são muito difíceis para mim.'],
    (object)['id' => 153, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Sinto-me tão resignado quanto à prova que não consigo começar a fazer nada.'],
    (object)['id' => 154, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Preferiria não fazer a prova porque perdi toda a esperança.'],
    (object)['id' => 155, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Sinto que quero desistir.'],
    (object)['id' => 156, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Minha desesperança me rouba toda a minha energia.'],
    (object)['id' => 157, 'emocao_id' => 24, 'classeaeq_id' => 3, 'pergunta_texto' => 'Eu me sinto tão resignado que não tenho energia.'],    
];

foreach ($records_questions as $record) {
    $DB->insert_record('ifcare_pergunta', $record);
}
}
?>
